version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "righettod"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '00:45'
