name: Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "**.java" 
  pull_request:
    branches: [ "main" ]
    paths:
    - "**.java"
    - "pom.xml"
permissions: read-all     
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - name: Install system requirements
      run: sudo apt-get update -y && sudo apt-get install -y dos2unix
    - name: Install JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Execute unit tests suite
      run: mvn clean test --file pom.xml
    - name: Update javadoc
      run: dos2unix update-javadoc.sh; chmod +x update-javadoc.sh; bash update-javadoc.sh

