name: Test
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system requirements
      run: sudo apt-get update && apt-get install -y dos2unix
    - name: Install JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Execute unit tests suite
      run: mvn clean test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --file pom.xml
    - name: Update javadoc
      run: dos2unix update-javadoc.sh; chmod +x update-javadoc.sh; bash update-javadoc.sh

